title: Pekka Astala - Developer of Software
email: pekka.astala@gmail.com
description: > #
    I'm a passionate software developer who enjoys programming both at work and during my time off.
    My work experience and technical expertise is centered around web development and related technologies.
baseurl: ""
url: "http://pekkaastala.github.io" # the base hostname & protocol for your site
twitter_username: PekkaAstala
github_username:  PekkaAstala

timezone: Europe/Helsinki
markdown: kramdown
theme: minima
