title: Pekka Astala - Developer of Software
email: pekka.astala@gmail.com
baseurl: ""
url: "https://pekkaastala.github.io" # the base hostname & protocol for your site
twitter_username: PekkaAstala
github_username:  PekkaAstala

timezone: Europe/Helsinki
markdown: kramdown
theme: minima
